on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Sean-Wu-HV/Black-duck-Scan@YKN-253
        with:
          input-args: '-h'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Blackduck Scan
        uses: addnab/docker-run-action@v3
        with:
            image: blackducksoftware/detect:8
            options: -v ${{ github.workspace }}:/workdir --entrypoint "/bin/bash"
            run: |
              java -jar /synopsys-detect.jar -h
              ls -la
              ls -la /workdir
